// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcahmbvekfcfxzjhumkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYWhtYnZla2ZjZnh6amh1bWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDc0NTcsImV4cCI6MjA1NDY4MzQ1N30.QV7hF0D957Hk_RLsTGdPnrd6lY2rOs8NC_T0FbYPShs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);